BRIDGE-2024: Add a request error metric
Sage-Bionetworks/BridgeWorkerPlatform-infra pull request #15
Opened 2018-01-18 18:52 UTC by zaro0508

Setup email notification when there are request errors.

2018-01-18 19:06 UTC, zaro0508 commented on cf_templates/eb_app.yml
> +      TreatMissingData: notBreaching
Need to manually set DefaultValue parameter, https://sagebionetworks.jira.com/browse/BRIDGE-1986

2018-01-18 19:06 UTC, zaro0508 commented on cf_templates/eb_app.yml
> +      TreatMissingData: notBreaching
same here

2018-01-18 20:48 UTC, DwayneJengSage requested changes

2018-01-18 20:48 UTC, DwayneJengSage commented on cf_templates/eb_app.yml
> +      Threshold: 10
Similarly, this should be 10 errors in 1 hour.

2018-01-18 20:48 UTC, DwayneJengSage commented on cf_templates/eb_app.yml
> +      Threshold: 100
And this should be 100 warnings in 1 hour.

2018-01-19 00:04 UTC, DwayneJengSage approved these changes

2018-01-19 00:45 UTC, merged